services:
  mysqldb:
    container_name: mysql-springboot
    image: mysql:8.0
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - $HOME/database:/var/lib/mysql
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: springboot_api
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      SERVICE_TAGS: prod
      SERVICE_NAME: mysqldb
    networks:
      - apinetwork

  restapi:
    container_name: restapi-springboot
    build: .
    image: restapi:1.0
    restart: unless-stopped
    ports:
      - 8080:8080
    expose:
      - 8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/springboot_api
      SPRING_DATASOURCE_USERNAME: 'root'
      SPRING_DATASOURCE_PASSWORD: 'password'
      SERVICE_TAGS: prod
      SERVICE_NAME: restapi
    depends_on:
      - 'mysqldb'
    networks:
      - apinetwork

networks:
  apinetwork:
    driver: bridge
